<a href="https://colab.research.google.com/github/yonehai/ML-labs/blob/main/lab2_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import unittest

In [20]:
def create_matrix(rows, columns):
  t = []
  m = []
  for i in range(0, rows):
    for j in range(0, columns):
      t.append(np.random.random())
    m.append(t)
    t = []
  return m

In [3]:
def matrix_multiply (matrix1, matrix2):
  sum = 0
  temp = []
  final_matrix = []
  if len(matrix2) != len(matrix1[0]):
    raise ValueError("Matrix cannot be multiplied")
  else:
    for z in range (0, len(matrix1)):
      for j in range(0, len(matrix2[0])):
        for i in range(0, len(matrix1[0])): 
          sum = sum + matrix1[z][i] * matrix2[i][j]
        temp.append(sum)
        sum = 0
      final_matrix.append(temp) 
      temp = []
    return final_matrix

In [6]:
print("Multiply two matrix")
matrix1 = create_matrix(10, 9)
matrix2= create_matrix(9, 5)
res = matrix_multiply(matrix1, matrix2)
print(res)

print("Multiply vector and matrix")
matrix1 = create_matrix(5, 3)
matrix2 = create_matrix(3, 1)
res = matrix_multiply(matrix1, matrix2)
print(res)

print("Multiply matrix and vector")
matrix1 = create_matrix(4, 1) 
matrix2 = create_matrix (1, 10)
res = matrix_multiply(matrix1, matrix2)
print(res)

Multiply two matrix
[[3.656493171456177, 1.8697910494232923, 3.6612687792841765, 3.4816015817853616, 2.2906097197554436], [2.5495883478746455, 1.1480556330394434, 2.734150097183259, 2.1397236429846043, 2.0929195553693054], [3.9232384698952427, 1.7503206101984403, 3.8927834554455147, 3.636467635956988, 2.760966769994202], [2.6735801082917905, 1.5812902721058752, 2.8819764076575236, 2.232933226405343, 1.7852362689020265], [3.605376384429203, 1.6897486514574136, 3.4526493538416525, 3.3395586815092098, 2.806029318889021], [3.172035097837975, 1.715595954781621, 3.161145969324352, 2.94811662029654, 2.377335583452983], [3.263584556399455, 1.4614170604977745, 3.0952121040037577, 3.585582365495174, 2.533917904883921], [2.274479261198599, 1.1678756293709802, 2.3679143112294314, 2.5066796074843802, 1.7578040983868657], [2.712410691234167, 1.4754151194258782, 3.117394824339269, 2.0671501558563277, 1.7005400538610136], [3.024973336654127, 1.365190758456773, 2.8392986740357715, 3.159816118671341, 2.

In [11]:
print("Multiply two matrix using numpy library")
A = create_matrix(3, 4)
B = create_matrix(4, 6)
print(np.dot(A, B))

print("Multiply vector and matrix")
A = create_matrix(6, 7) 
B = create_matrix(7, 1)
print(np.dot(A, B))

print("Multiply matrix and vector") 
A = create_matrix(4, 1) 
B = create_matrix(1, 9)
print(np.dot(A, B))

Multiply two matrix using numpy library
[[0.60286449 0.53184624 0.93801494 0.43607656 1.17701338 0.47613408]
 [0.63147587 0.74600468 0.94819334 0.94864288 1.1840004  1.04387139]
 [0.9033476  0.60293893 1.14707041 0.86707038 1.34140868 1.38960874]]
Multiply vector and matrix
[[2.54434101]
 [2.66398421]
 [2.80093065]
 [1.54997528]
 [1.89648273]
 [2.23195303]]
Multiply matrix and vector
[[0.35763522 0.33037863 0.18808672 0.16827706 0.15636611 0.08897909
  0.34771321 0.24171487 0.32988155]
 [0.65850311 0.60831635 0.34631849 0.30984356 0.28791226 0.16383455
  0.640234   0.4450624  0.6074011 ]
 [0.32627233 0.30140601 0.17159242 0.15351997 0.14265355 0.08117605
  0.31722043 0.22051763 0.30095252]
 [0.9050676  0.83608933 0.47599115 0.42585883 0.39571577 0.22517941
  0.87995796 0.61170791 0.83483138]]
